export type Features = {
    id: number,
    descriptions: boolean,
    eras: boolean,
    multiple_sources: boolean,
    reviews: boolean,
    ratings: boolean,
    tours: boolean,
    taper_notes: boolean,
    source_information: boolean,
    sets: boolean,
    per_show_venues: boolean,
    per_source_venues: boolean,
    venue_coords: boolean,
    songs: boolean,
    years: boolean,
    track_md5s: boolean,
    review_titles: boolean,
    jam_charts: boolean,
    setlist_data_incomplete: boolean,
    artist_id: number,
    track_names: boolean,
    venue_past_names: boolean,
    reviews_have_ratings: boolean,
    track_durations: boolean,
    can_have_flac: boolean;
}